name: Model Architecture Checks

on:
  push:
    branches: [ main ]
    paths:
      - 'Assignment_6/**'  # Triggers only if files in Assignment_6/ are changed
  pull_request:
    branches: [ main ]
    paths:
      - 'Assignment_6/**'  # Triggers only if files in Assignment_6/ are changed

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r Assignment_6/requirements.txt  # Update path to requirements.txt inside Assignment_6
    
    - name: Run tests
      run: |
        pytest Assignment_6/test_model.py -v  # Update path to test_model.py inside Assignment_6
